// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: birthday.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const listGroupMatesForUser = `-- name: ListGroupMatesForUser :many
SELECT DISTINCT u.id, u.email, u.password_hash, u.birthday, u.birthday_self_notify, u.birthday_member_notify, u.post_notify, u.created_at, u.updated_at
FROM users u
INNER JOIN group_members gm ON gm.user_id = u.id
WHERE gm.group_id IN (SELECT gm_self.group_id FROM group_members gm_self WHERE gm_self.user_id = $1)
  AND u.id != $1
`

func (q *Queries) ListGroupMatesForUser(ctx context.Context, userID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listGroupMatesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Birthday,
			&i.BirthdaySelfNotify,
			&i.BirthdayMemberNotify,
			&i.PostNotify,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodayBirthdayUsersJST = `-- name: ListTodayBirthdayUsersJST :many
SELECT id, email, password_hash, birthday, birthday_self_notify, birthday_member_notify, post_notify, created_at, updated_at FROM users
WHERE EXTRACT(MONTH FROM birthday) = EXTRACT(MONTH FROM (NOW() AT TIME ZONE 'Asia/Tokyo'))
  AND EXTRACT(DAY FROM birthday) = EXTRACT(DAY FROM (NOW() AT TIME ZONE 'Asia/Tokyo'))
`

func (q *Queries) ListTodayBirthdayUsersJST(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listTodayBirthdayUsersJST)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Birthday,
			&i.BirthdaySelfNotify,
			&i.BirthdayMemberNotify,
			&i.PostNotify,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
