// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_logs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailLog = `-- name: CreateEmailLog :one
INSERT INTO email_logs (recipient_user_id, email_type, recipient_email, subject, status)
VALUES ($1, $2, $3, $4, 'pending')
RETURNING id, recipient_user_id, email_type, recipient_email, subject, status, error_message, sent_at, created_at
`

type CreateEmailLogParams struct {
	RecipientUserID uuid.UUID `db:"recipient_user_id" json:"recipient_user_id"`
	EmailType       string    `db:"email_type" json:"email_type"`
	RecipientEmail  string    `db:"recipient_email" json:"recipient_email"`
	Subject         string    `db:"subject" json:"subject"`
}

func (q *Queries) CreateEmailLog(ctx context.Context, arg CreateEmailLogParams) (EmailLog, error) {
	row := q.db.QueryRow(ctx, createEmailLog,
		arg.RecipientUserID,
		arg.EmailType,
		arg.RecipientEmail,
		arg.Subject,
	)
	var i EmailLog
	err := row.Scan(
		&i.ID,
		&i.RecipientUserID,
		&i.EmailType,
		&i.RecipientEmail,
		&i.Subject,
		&i.Status,
		&i.ErrorMessage,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const hasSentEmailToday = `-- name: HasSentEmailToday :one
SELECT EXISTS(
    SELECT 1 FROM email_logs
    WHERE recipient_user_id = $1
      AND email_type = $2
      AND status = 'sent'
      AND DATE(sent_at AT TIME ZONE 'Asia/Tokyo') = DATE(NOW() AT TIME ZONE 'Asia/Tokyo')
) AS has_sent
`

type HasSentEmailTodayParams struct {
	RecipientUserID uuid.UUID `db:"recipient_user_id" json:"recipient_user_id"`
	EmailType       string    `db:"email_type" json:"email_type"`
}

func (q *Queries) HasSentEmailToday(ctx context.Context, arg HasSentEmailTodayParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasSentEmailToday, arg.RecipientUserID, arg.EmailType)
	var has_sent bool
	err := row.Scan(&has_sent)
	return has_sent, err
}

const markEmailLogFailed = `-- name: MarkEmailLogFailed :exec
UPDATE email_logs
SET status = 'failed', error_message = $2
WHERE id = $1
`

type MarkEmailLogFailedParams struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	ErrorMessage pgtype.Text `db:"error_message" json:"error_message"`
}

func (q *Queries) MarkEmailLogFailed(ctx context.Context, arg MarkEmailLogFailedParams) error {
	_, err := q.db.Exec(ctx, markEmailLogFailed, arg.ID, arg.ErrorMessage)
	return err
}

const markEmailLogSent = `-- name: MarkEmailLogSent :exec
UPDATE email_logs
SET status = 'sent', sent_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkEmailLogSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEmailLogSent, id)
	return err
}
