// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: group_members.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupMember = `-- name: AddGroupMember :one
INSERT INTO group_members (user_id, group_id, display_name, icon_url, role)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, group_id, display_name, icon_url, role, joined_at
`

type AddGroupMemberParams struct {
	UserID      uuid.UUID   `db:"user_id" json:"user_id"`
	GroupID     uuid.UUID   `db:"group_id" json:"group_id"`
	DisplayName string      `db:"display_name" json:"display_name"`
	IconUrl     pgtype.Text `db:"icon_url" json:"icon_url"`
	Role        string      `db:"role" json:"role"`
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, addGroupMember,
		arg.UserID,
		arg.GroupID,
		arg.DisplayName,
		arg.IconUrl,
		arg.Role,
	)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.DisplayName,
		&i.IconUrl,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getGroupMember = `-- name: GetGroupMember :one
SELECT id, user_id, group_id, display_name, icon_url, role, joined_at FROM group_members
WHERE user_id = $1 AND group_id = $2
LIMIT 1
`

type GetGroupMemberParams struct {
	UserID  uuid.UUID `db:"user_id" json:"user_id"`
	GroupID uuid.UUID `db:"group_id" json:"group_id"`
}

func (q *Queries) GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, getGroupMember, arg.UserID, arg.GroupID)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.DisplayName,
		&i.IconUrl,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const isGroupMember = `-- name: IsGroupMember :one
SELECT EXISTS(
    SELECT 1 FROM group_members
    WHERE user_id = $1 AND group_id = $2
) AS is_member
`

type IsGroupMemberParams struct {
	UserID  uuid.UUID `db:"user_id" json:"user_id"`
	GroupID uuid.UUID `db:"group_id" json:"group_id"`
}

func (q *Queries) IsGroupMember(ctx context.Context, arg IsGroupMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isGroupMember, arg.UserID, arg.GroupID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT id, user_id, group_id, display_name, icon_url, role, joined_at FROM group_members
WHERE group_id = $1
ORDER BY joined_at ASC
`

func (q *Queries) ListGroupMembers(ctx context.Context, groupID uuid.UUID) ([]GroupMember, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupMember
	for rows.Next() {
		var i GroupMember
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.DisplayName,
			&i.IconUrl,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroupMemberProfile = `-- name: UpdateGroupMemberProfile :one
UPDATE group_members
SET display_name = $3, icon_url = $4
WHERE user_id = $1 AND group_id = $2
RETURNING id, user_id, group_id, display_name, icon_url, role, joined_at
`

type UpdateGroupMemberProfileParams struct {
	UserID      uuid.UUID   `db:"user_id" json:"user_id"`
	GroupID     uuid.UUID   `db:"group_id" json:"group_id"`
	DisplayName string      `db:"display_name" json:"display_name"`
	IconUrl     pgtype.Text `db:"icon_url" json:"icon_url"`
}

func (q *Queries) UpdateGroupMemberProfile(ctx context.Context, arg UpdateGroupMemberProfileParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, updateGroupMemberProfile,
		arg.UserID,
		arg.GroupID,
		arg.DisplayName,
		arg.IconUrl,
	)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.DisplayName,
		&i.IconUrl,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}
