// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invite_links.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInviteLink = `-- name: CreateInviteLink :one
INSERT INTO invite_links (group_id, token, created_by_user_id, expires_at, max_uses)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, group_id, token, created_by_user_id, expires_at, max_uses, current_uses, created_at
`

type CreateInviteLinkParams struct {
	GroupID         uuid.UUID          `db:"group_id" json:"group_id"`
	Token           string             `db:"token" json:"token"`
	CreatedByUserID uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	ExpiresAt       pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	MaxUses         int32              `db:"max_uses" json:"max_uses"`
}

func (q *Queries) CreateInviteLink(ctx context.Context, arg CreateInviteLinkParams) (InviteLink, error) {
	row := q.db.QueryRow(ctx, createInviteLink,
		arg.GroupID,
		arg.Token,
		arg.CreatedByUserID,
		arg.ExpiresAt,
		arg.MaxUses,
	)
	var i InviteLink
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Token,
		&i.CreatedByUserID,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.CurrentUses,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredInviteLinks = `-- name: DeleteExpiredInviteLinks :exec
DELETE FROM invite_links
WHERE expires_at <= NOW() OR current_uses >= max_uses
`

func (q *Queries) DeleteExpiredInviteLinks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredInviteLinks)
	return err
}

const getInviteLink = `-- name: GetInviteLink :one
SELECT id, group_id, token, created_by_user_id, expires_at, max_uses, current_uses, created_at FROM invite_links
WHERE token = $1
  AND expires_at > NOW()
  AND current_uses < max_uses
LIMIT 1
`

func (q *Queries) GetInviteLink(ctx context.Context, token string) (InviteLink, error) {
	row := q.db.QueryRow(ctx, getInviteLink, token)
	var i InviteLink
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Token,
		&i.CreatedByUserID,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.CurrentUses,
		&i.CreatedAt,
	)
	return i, err
}

const incrementInviteLinkUses = `-- name: IncrementInviteLinkUses :exec
UPDATE invite_links
SET current_uses = current_uses + 1
WHERE token = $1
`

func (q *Queries) IncrementInviteLinkUses(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, incrementInviteLinkUses, token)
	return err
}
