// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailLog struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	RecipientUserID uuid.UUID          `db:"recipient_user_id" json:"recipient_user_id"`
	EmailType       string             `db:"email_type" json:"email_type"`
	RecipientEmail  string             `db:"recipient_email" json:"recipient_email"`
	Subject         string             `db:"subject" json:"subject"`
	Status          string             `db:"status" json:"status"`
	ErrorMessage    pgtype.Text        `db:"error_message" json:"error_message"`
	SentAt          pgtype.Timestamptz `db:"sent_at" json:"sent_at"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Group struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	Name            string             `db:"name" json:"name"`
	Description     pgtype.Text        `db:"description" json:"description"`
	CreatedByUserID uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type GroupMember struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	GroupID     uuid.UUID          `db:"group_id" json:"group_id"`
	DisplayName string             `db:"display_name" json:"display_name"`
	IconUrl     pgtype.Text        `db:"icon_url" json:"icon_url"`
	Role        string             `db:"role" json:"role"`
	JoinedAt    pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
}

type InviteLink struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	GroupID         uuid.UUID          `db:"group_id" json:"group_id"`
	Token           string             `db:"token" json:"token"`
	CreatedByUserID uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	ExpiresAt       pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	MaxUses         int32              `db:"max_uses" json:"max_uses"`
	CurrentUses     int32              `db:"current_uses" json:"current_uses"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Post struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	GroupID      uuid.UUID          `db:"group_id" json:"group_id"`
	AuthorUserID uuid.UUID          `db:"author_user_id" json:"author_user_id"`
	Body         string             `db:"body" json:"body"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type PostImage struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	PostID    uuid.UUID          `db:"post_id" json:"post_id"`
	ImageUrl  string             `db:"image_url" json:"image_url"`
	SortOrder int32              `db:"sort_order" json:"sort_order"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Session struct {
	ID        string             `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	Email                string             `db:"email" json:"email"`
	PasswordHash         string             `db:"password_hash" json:"password_hash"`
	Birthday             pgtype.Date        `db:"birthday" json:"birthday"`
	BirthdaySelfNotify   bool               `db:"birthday_self_notify" json:"birthday_self_notify"`
	BirthdayMemberNotify bool               `db:"birthday_member_notify" json:"birthday_member_notify"`
	PostNotify           bool               `db:"post_notify" json:"post_notify"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
