// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post_shares.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createPostShare = `-- name: CreatePostShare :one
INSERT INTO post_shares (post_id, group_id)
VALUES ($1, $2)
RETURNING id, post_id, group_id, shared_at
`

type CreatePostShareParams struct {
	PostID  uuid.UUID `db:"post_id" json:"post_id"`
	GroupID uuid.UUID `db:"group_id" json:"group_id"`
}

func (q *Queries) CreatePostShare(ctx context.Context, arg CreatePostShareParams) (PostShare, error) {
	row := q.db.QueryRow(ctx, createPostShare, arg.PostID, arg.GroupID)
	var i PostShare
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.GroupID,
		&i.SharedAt,
	)
	return i, err
}

const deletePostShare = `-- name: DeletePostShare :exec
DELETE FROM post_shares
WHERE post_id = $1 AND group_id = $2
`

type DeletePostShareParams struct {
	PostID  uuid.UUID `db:"post_id" json:"post_id"`
	GroupID uuid.UUID `db:"group_id" json:"group_id"`
}

func (q *Queries) DeletePostShare(ctx context.Context, arg DeletePostShareParams) error {
	_, err := q.db.Exec(ctx, deletePostShare, arg.PostID, arg.GroupID)
	return err
}
