// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post_images.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const canAccessPostImage = `-- name: CanAccessPostImage :one
SELECT EXISTS (
    SELECT 1
    FROM post_images pi
    JOIN posts p ON p.id = pi.post_id
    WHERE pi.image_url LIKE '%/' || $1
      AND p.deleted_at IS NULL
      AND (
        p.author_user_id = $2
        OR EXISTS (
            SELECT 1
            FROM post_shares ps
            JOIN group_members gm ON gm.group_id = ps.group_id
            WHERE ps.post_id = p.id AND gm.user_id = $2
        )
      )
) AS allowed
`

type CanAccessPostImageParams struct {
	Filename string    `db:"filename" json:"filename"`
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
}

// 指定ファイル名の画像にリクエストユーザーがアクセスできるか判定する。
// 許可条件:
//  1. 投稿の著者本人である ( p.author_user_id = user_id )
//  2. その投稿がシェアされているいずれかのグループのメンバーである
//
// 画像ファイル名 ($1) を image_url の末尾とマッチさせて post を逆引き。
func (q *Queries) CanAccessPostImage(ctx context.Context, arg CanAccessPostImageParams) (bool, error) {
	row := q.db.QueryRow(ctx, canAccessPostImage, arg.Filename, arg.UserID)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const addPostImage = `-- name: AddPostImage :one
INSERT INTO post_images (post_id, image_url, sort_order)
VALUES ($1, $2, $3)
RETURNING id, post_id, image_url, sort_order, created_at
`

type AddPostImageParams struct {
	PostID    uuid.UUID `db:"post_id" json:"post_id"`
	ImageUrl  string    `db:"image_url" json:"image_url"`
	SortOrder int32     `db:"sort_order" json:"sort_order"`
}

func (q *Queries) AddPostImage(ctx context.Context, arg AddPostImageParams) (PostImage, error) {
	row := q.db.QueryRow(ctx, addPostImage, arg.PostID, arg.ImageUrl, arg.SortOrder)
	var i PostImage
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ImageUrl,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listPostImages = `-- name: ListPostImages :many
SELECT id, post_id, image_url, sort_order, created_at FROM post_images
WHERE post_id = $1
ORDER BY sort_order ASC
`

func (q *Queries) ListPostImages(ctx context.Context, postID uuid.UUID) ([]PostImage, error) {
	rows, err := q.db.Query(ctx, listPostImages, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostImage
	for rows.Next() {
		var i PostImage
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ImageUrl,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
