// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (group_id, author_user_id, body)
VALUES ($1, $2, $3)
RETURNING id, group_id, author_user_id, body, created_at, updated_at, deleted_at
`

type CreatePostParams struct {
	GroupID      uuid.UUID `db:"group_id" json:"group_id"`
	AuthorUserID uuid.UUID `db:"author_user_id" json:"author_user_id"`
	Body         string    `db:"body" json:"body"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost, arg.GroupID, arg.AuthorUserID, arg.Body)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.AuthorUserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPost = `-- name: GetPost :one
SELECT id, group_id, author_user_id, body, created_at, updated_at, deleted_at FROM posts
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetPost(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.AuthorUserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listGroupPosts = `-- name: ListGroupPosts :many
SELECT
    p.id,
    p.group_id,
    p.author_user_id,
    p.body,
    p.created_at,
    gm.display_name AS author_display_name,
    gm.icon_url AS author_icon_url
FROM posts p
INNER JOIN group_members gm
    ON gm.user_id = p.author_user_id AND gm.group_id = p.group_id
WHERE p.group_id = $1 AND p.deleted_at IS NULL
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type ListGroupPostsParams struct {
	GroupID uuid.UUID `db:"group_id" json:"group_id"`
	Limit   int32     `db:"limit" json:"limit"`
	Offset  int32     `db:"offset" json:"offset"`
}

type ListGroupPostsRow struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	GroupID           uuid.UUID          `db:"group_id" json:"group_id"`
	AuthorUserID      uuid.UUID          `db:"author_user_id" json:"author_user_id"`
	Body              string             `db:"body" json:"body"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	AuthorDisplayName string             `db:"author_display_name" json:"author_display_name"`
	AuthorIconUrl     pgtype.Text        `db:"author_icon_url" json:"author_icon_url"`
}

func (q *Queries) ListGroupPosts(ctx context.Context, arg ListGroupPostsParams) ([]ListGroupPostsRow, error) {
	rows, err := q.db.Query(ctx, listGroupPosts, arg.GroupID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupPostsRow
	for rows.Next() {
		var i ListGroupPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.AuthorUserID,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorDisplayName,
			&i.AuthorIconUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimeline = `-- name: ListTimeline :many
SELECT
    p.id,
    p.group_id,
    p.author_user_id,
    p.body,
    p.created_at,
    g.name AS group_name,
    gm.display_name AS author_display_name,
    gm.icon_url AS author_icon_url
FROM posts p
INNER JOIN groups g ON g.id = p.group_id
INNER JOIN group_members gm
    ON gm.user_id = p.author_user_id AND gm.group_id = p.group_id
WHERE p.group_id IN (
    SELECT gm_timeline.group_id FROM group_members gm_timeline WHERE gm_timeline.user_id = $1
)
  AND p.deleted_at IS NULL
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type ListTimelineParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

type ListTimelineRow struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	GroupID           uuid.UUID          `db:"group_id" json:"group_id"`
	AuthorUserID      uuid.UUID          `db:"author_user_id" json:"author_user_id"`
	Body              string             `db:"body" json:"body"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	GroupName         string             `db:"group_name" json:"group_name"`
	AuthorDisplayName string             `db:"author_display_name" json:"author_display_name"`
	AuthorIconUrl     pgtype.Text        `db:"author_icon_url" json:"author_icon_url"`
}

func (q *Queries) ListTimeline(ctx context.Context, arg ListTimelineParams) ([]ListTimelineRow, error) {
	rows, err := q.db.Query(ctx, listTimeline, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimelineRow
	for rows.Next() {
		var i ListTimelineRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.AuthorUserID,
			&i.Body,
			&i.CreatedAt,
			&i.GroupName,
			&i.AuthorDisplayName,
			&i.AuthorIconUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePost = `-- name: SoftDeletePost :exec
UPDATE posts SET deleted_at = NOW()
WHERE id = $1 AND author_user_id = $2
`

type SoftDeletePostParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	AuthorUserID uuid.UUID `db:"author_user_id" json:"author_user_id"`
}

func (q *Queries) SoftDeletePost(ctx context.Context, arg SoftDeletePostParams) error {
	_, err := q.db.Exec(ctx, softDeletePost, arg.ID, arg.AuthorUserID)
	return err
}
