// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddGroupMember(ctx context.Context, arg AddGroupMemberParams) (GroupMember, error)
	AddPostImage(ctx context.Context, arg AddPostImageParams) (PostImage, error)
	// 指定ファイル名の画像にリクエストユーザーがアクセスできるか判定する。
	// 許可条件:
	//  1. 投稿の著者本人である ( p.author_user_id = user_id )
	//  2. その投稿がシェアされているいずれかのグループのメンバーである
	//
	// 画像ファイル名 ($1) を image_url の末尾とマッチさせて post を逆引き。
	CanAccessPostImage(ctx context.Context, arg CanAccessPostImageParams) (bool, error)
	CreateEmailLog(ctx context.Context, arg CreateEmailLogParams) (EmailLog, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateInviteLink(ctx context.Context, arg CreateInviteLinkParams) (InviteLink, error)
	// =====================================================
	// マイルストーン (posts) クエリ群
	// group_id を持たない設計に書き換え (post_shares で多対多関係)
	// =====================================================
	// マイルストーンを新規作成 (シェア先は別途 post_shares に追加)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreatePostShare(ctx context.Context, arg CreatePostShareParams) (PostShare, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredInviteLinks(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context) error
	DeletePostShare(ctx context.Context, arg DeletePostShareParams) error
	DeleteSession(ctx context.Context, id string) error
	GetGroup(ctx context.Context, id uuid.UUID) (Group, error)
	GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GroupMember, error)
	GetInviteLink(ctx context.Context, token string) (InviteLink, error)
	// 単一マイルストーン取得 (削除済みは除外)
	GetPost(ctx context.Context, id uuid.UUID) (Post, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	HasSentEmailToday(ctx context.Context, arg HasSentEmailTodayParams) (bool, error)
	IncrementInviteLinkUses(ctx context.Context, token string) error
	IsGroupMember(ctx context.Context, arg IsGroupMemberParams) (bool, error)
	ListGroupMatesForUser(ctx context.Context, userID uuid.UUID) ([]User, error)
	ListGroupMembers(ctx context.Context, groupID uuid.UUID) ([]GroupMember, error)
	// 特定グループにシェアされたマイルストーン (フィルタチップ「○○グループ」選択時)
	// 表示名はそのグループでの display_name を使う
	ListGroupPosts(ctx context.Context, arg ListGroupPostsParams) ([]ListGroupPostsRow, error)
	// 自分のマイルストーン (シェア有無問わず、フィルタチップ「マイ記録」選択時)
	ListMyMilestones(ctx context.Context, arg ListMyMilestonesParams) ([]ListMyMilestonesRow, error)
	ListPostImages(ctx context.Context, postID uuid.UUID) ([]PostImage, error)
	// 統合タイムライン: 自分のマイルストーン + 所属グループにシェアされた他人のマイルストーン
	// 表示名は「最初にシェアされたグループでの著者名」、
	// 0シェアの場合は「著者が最初に参加したグループでの著者名」をフォールバック
	ListTimeline(ctx context.Context, arg ListTimelineParams) ([]ListTimelineRow, error)
	ListTodayBirthdayUsersJST(ctx context.Context) ([]User, error)
	ListUserGroups(ctx context.Context, userID uuid.UUID) ([]ListUserGroupsRow, error)
	MarkEmailLogFailed(ctx context.Context, arg MarkEmailLogFailedParams) error
	MarkEmailLogSent(ctx context.Context, id uuid.UUID) error
	// 自分の投稿のみ論理削除可能
	SoftDeletePost(ctx context.Context, arg SoftDeletePostParams) error
	UpdateGroupMemberProfile(ctx context.Context, arg UpdateGroupMemberProfileParams) (GroupMember, error)
}

var _ Querier = (*Queries)(nil)
