// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, birthday)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, birthday, birthday_self_notify, birthday_member_notify, post_notify, created_at, updated_at
`

type CreateUserParams struct {
	Email        string      `db:"email" json:"email"`
	PasswordHash string      `db:"password_hash" json:"password_hash"`
	Birthday     pgtype.Date `db:"birthday" json:"birthday"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Birthday)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Birthday,
		&i.BirthdaySelfNotify,
		&i.BirthdayMemberNotify,
		&i.PostNotify,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, birthday, birthday_self_notify, birthday_member_notify, post_notify, created_at, updated_at FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Birthday,
		&i.BirthdaySelfNotify,
		&i.BirthdayMemberNotify,
		&i.PostNotify,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
